CC=g++
#CC=clang++
#CFLAGS=-Wall -Wextra -std=c++11 -g -O0 -DJASON_DEBUG -DJASON_VALIDATEUTF8
#CFLAGS=-Wall -Wextra -std=c++11 -g -O3 
#CFLAGS=-Wall -Wextra -std=c++11 -g -O3 -DRAPIDJSON_SSE42 -march=native -msse4.2
CFLAGS=-Wall -Wextra -std=c++11 -g -O3 -DRAPIDJSON_SSE42 -march=native
#CFLAGS=-Wall -Wextra -std=c++11 -g -O3 -march=native -msse4.2 -DNO_SSE42
#CFLAGS=-Wall -Wextra -std=c++11 -g -O3 -march=native -msse4.2
#CFLAGS=-Wall -Wextra -std=c++11 -g -O3 -msse4.2
#CFLAGS=-Wall -Wextra -std=c++11 -g -O0 -DNO_SSE42
#CFLAGS=-Wall -Wextra -std=c++11 -g -O3 -DJASON_VALIDATEUTF8 
#CFLAGS=-Wall -Wextra -std=c++11 -g -O0 -DJASON_DEBUG -DJASON_VALIDATEUTF8

all:	test bench JasonAsm

.PHONY: googletest

googletest:
	rm -Rf googletest
	git clone https://github.com/google/googletest.git
	cd googletest/googletest && $(CC) -isystem ./include/ -I. -pthread -c ./src/gtest-all.cc
	cd googletest/googletest && ar -rv libgtest.a gtest-all.o

fpconv.o: Makefile.old powers.h fpconv.h fpconv.cpp
	$(CC) $(CFLAGS) fpconv.cpp -c -o fpconv.o

JasonAsm.o: Makefile.old JasonAsm.h JasonAsm.cpp
	$(CC) $(CFLAGS) JasonAsm.cpp -c -o JasonAsm.o

JasonParser.o: Makefile.old JasonAsm.h JasonParser.h JasonParser.cpp
	$(CC) $(CFLAGS) JasonParser.cpp -c -o JasonParser.o

JasonBuilder.o: Makefile.old JasonAsm.h JasonParser.h JasonBuilder.h JasonBuilder.cpp
	$(CC) $(CFLAGS) JasonBuilder.cpp -c -o JasonBuilder.o

Jason.o: Makefile.old Jason.h JasonBuilder.h JasonDumper.h JasonParser.h JasonSlice.h JasonType.h Jason.cpp
	$(CC) $(CFLAGS) Jason.cpp -c -o Jason.o

test:	Makefile.old test.cpp fpconv.o Jason.h Jason.o JasonAsm.o JasonParser.o JasonBuilder.o
	$(CC) $(CFLAGS) -Igoogletest/googletest/include test.cpp fpconv.o Jason.o JasonAsm.o JasonParser.o JasonBuilder.o googletest/googletest/libgtest.a -pthread -o test

bench: Makefile.old bench.cpp fpconv.o Jason.h Jason.o JasonAsm.o JasonParser.o JasonBuilder.o
	$(CC) $(CFLAGS) bench.cpp fpconv.o Jason.o JasonAsm.o JasonParser.o JasonBuilder.o -o bench

JasonAsm: Makefile.old JasonAsm.h JasonAsm.cpp
	$(CC) $(CFLAGS) JasonAsm.cpp -DCOMPILE_JASONASM_UNITTESTS -o JasonAsm

clean:	
	rm -rf *.o test bench
